#!/bin/bash

set -e

# Not really using these yet:
PROJECT=$1


sudo apt-get install -y emacs24 curl tree unzip zip mosh openjdk-7-jdk

mkdir -p ~/bin
wget -qO ~/bin/lein https://raw.github.com/technomancy/leiningen/stable/bin/lein
chmod +x ~/bin/lein

sudo apt-get install -y emacs24

cd $(dirname $0)


sudo cp hub ~/bin

cp .emacs ~
cp .bashrc ~
cp .gemrc ~
cp .gitconfig ~
cp .profile ~
cp .tmux.conf ~

