#!/bin/bash

set -e

# Not really using these yet:
PROJECT=$1

sudo apt-get install -y emacs24 curl tree unzip zip mosh openjdk-7-jdk

cd $(dirname $0)

cp .emacs ~
cp .bashrc ~
cp .gemrc ~
cp .gitconfig ~
cp .profile ~
cp .tmux.conf ~

mkdir -p ~/bin

sudo cp hub ~/bin

wget -qO ~/bin/lein https://raw.github.com/technomancy/leiningen/stable/bin/lein
chmod +x ~/bin/lein
